theme: jekyll-theme-cayman
title: UTSC Undergraduate Research Society
description: This website brings together undergraduate computer science students and stakeholders interested in developing research skills
